name: uppert-selftest
on: 
  push:

jobs:
    build:
        name: upper-application
        runs-on: ubuntu-latest
        steps:
          - run: pwd && ls -la
          - uses: actions/checkout@v4
          - run: pwd && ls -la
          - run: go version 
          - uses: actions/setup-go@v5
            with:
              go-version: '1.22.12'
          - run: go version