name: uppert-selftest
on: 
  push:
     paths: 
        - ".github/workflows/upper-adil.yml"

jobs:
    build:
        name: upper-application
        runs-on: ubuntu-latest
        steps:
          - run: pwd && ls -la
          - uses: actions/checkout@v4
          - run: pwd && ls -la
          - run: go version 
          - uses: actions/setup-go@v5
            with:
              #go-version: '1.22.12'
              go-version-file: ./upper/go.mod
          - run: go version
          - run: | 
              ls
              go build
              ls
              go test
              ./upper foo the bar
            working-directory: upper